# Generated by Django 2.2a1 on 2019-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
                ('fid', models.CharField(max_length=50, unique=True, verbose_name='Facility ZW ID')),
                ('fuid', models.CharField(max_length=255, unique=True, verbose_name='Facility UID')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
