# Generated by Django 2.2a1 on 2019-02-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True, verbose_name='Sample ID')),
                ('pruid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient UID')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Result')),
                ('state', models.CharField(choices=[('Received', 'Received'), ('Verified', 'Verified'), ('Published', 'Published')], default='Received', max_length=20, verbose_name='Review State')),
                ('date_sampled', models.DateTimeField(blank=True, null=True, verbose_name='Date Sampled')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_received', models.DateTimeField(blank=True, null=True, verbose_name='Date Received')),
                ('date_captured', models.DateTimeField(blank=True, null=True, verbose_name='Date Captured')),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(choices=[('H12PCAP', 'H12PCAP'), ('ABBOT', 'ABBOT')], default='H12PCAP', max_length=10, verbose_name='Instrument Keyword')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
