# Generated by Django 2.2a1 on 2019-02-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyses',
            options={'verbose_name': 'Analyses', 'verbose_name_plural': 'Analyses'},
        ),
    ]
