# Generated by Django 2.2.2 on 2019-06-16 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_api', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sync Detail',
                'verbose_name_plural': 'Sync Details',
            },
        ),
        migrations.CreateModel(
            name='SyncProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_done', models.BooleanField(default=False)),
                ('client_total', models.PositiveIntegerField()),
                ('client_count', models.PositiveIntegerField()),
                ('client_synced', models.DateTimeField()),
                ('patient_done', models.BooleanField(default=False)),
                ('patient_total', models.PositiveIntegerField()),
                ('patient_count', models.PositiveIntegerField()),
                ('patient_synced', models.DateTimeField()),
                ('analysis_done', models.BooleanField(default=False)),
                ('analysis_total', models.PositiveIntegerField()),
                ('analysis_count', models.PositiveIntegerField()),
                ('analysis_synced', models.DateTimeField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_progress_login', to='sync.SyncLogin')),
            ],
        ),
        migrations.CreateModel(
            name='SyncPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('page_size', models.PositiveIntegerField()),
                ('iterations', models.PositiveIntegerField()),
                ('descending', models.BooleanField(default=True)),
                ('page_nr', models.PositiveIntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sync.SyncLogin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('page_size', models.PositiveIntegerField()),
                ('iterations', models.PositiveIntegerField()),
                ('descending', models.BooleanField(default=True)),
                ('page_nr', models.PositiveIntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sync.SyncLogin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=255)),
                ('page_size', models.PositiveIntegerField()),
                ('iterations', models.PositiveIntegerField()),
                ('descending', models.BooleanField(default=True)),
                ('page_nr', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('verified', 'verified'), ('published', 'published'), ('All', 'All')], default='published', max_length=255)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sync.SyncLogin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
