# Generated by Django 2.2.2 on 2019-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.BooleanField(default=False)),
                ('clients', models.BooleanField(default=False)),
                ('analyses', models.BooleanField(default=False)),
            ],
        ),
    ]
