# Generated by Django 2.2.2 on 2019-06-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncseletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncseletion',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sync_selection_login', to='sync.SyncLogin'),
            preserve_default=False,
        ),
    ]
