# Generated by Django 2.2a1 on 2019-02-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='', max_length=6, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('cpid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Patient ID')),
                ('puid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Patient UID')),
                ('pruid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Referrer UID')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility.Facility')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
